### ISSUE TITLE
메인 페이지 웹 접근성 및 이미지 확장자 변경

### ISSUE THREAD

**Issue by happyhye** [FRONTENDSCHOOL10/Code12hour#33]
## 📄 설명

중간 점검 시간에 받은 피드백을 바탕으로
메인 페이지 웹 접근성 및 성능을 향상하고자 함

## 📋 TO-DO

- [ ] 이미지 대체 텍스트 수정
- [ ] 불필요한 aria-label 삭제
- [ ] 이미지 확장자 변경 (기존 jpg → webp)

## 🔔 기타

아직 완성하지 못한 다른 컴포넌트 먼저 마크업 후 메인 페이지 수정 예정
