### ISSUE TITLE
헤더, 푸터, 상품 상세, 장바구니 페이지 마크업 리팩토링

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Code12hour#37]
## 📄 설명

헤더, 푸터, 상품 상세, 장바구니 페이지 마크업에 대한 리팩토링

## 📋 TO-DO

- [ ] 헤더 마크업 리팩토링
- [ ] 푸터 마크업 리팩토링
- [ ] 상품 상세 페이지 리팩토링
- [ ] 상품 장바구니 페이지 리팩토링
