### ISSUE TITLE
메인 배너 슬라이드, 상품 리스트, 프로모션 배너, 추천 상품 리스트 마크업

### ISSUE THREAD

**Issue by happyhye** [FRONTENDSCHOOL10/Code12hour#4]
## 📄 설명

메인 배너 슬라이드, 상품 리스트, 프로모션 배너, 추천 상품 리스트 마크업

## 📋 TO-DO

- [ ] 메인 배너 슬라이드 마크업
- [ ] 상품 리스트  마크업
- [ ] 프로모션 배너 마크업
- [ ] 추천 상품 리스트 마크업

## 🔔 기타

재사용성을 고려하여 마크업하기
