### ISSUE TITLE
상품 디테일: 상품 문의 섹션 기능 구현

### ISSUE THREAD

**Issue by soyeonpaark** [FRONTENDSCHOOL10/Code12hour#49]
## 📄 설명

상품 문의 섹션 기능 구현

## 📋 TO-DO

- [x] 문의하기 작성 가능 (모달창 열기 / 닫기)
- [x] textarea 포커스 시 내부 텍스트 삭제
- [x] 입력 글자 수 카운터
- [x] 제목, 내용 입력 시 등록 버튼 활성화
- [x] 후기 작성 시 내용 입력 및 작성 날짜 반영
- [ ] 리뷰 유무에 따른 디스플레이
- [ ] 리뷰 개수 업데이트 기능
- [ ] 비밀글 팝업창
- [ ] (부가기능) 답변 상태

## 🔔 기타

기타 사항을 적어주세요.
