### ISSUE TITLE
상품 디테일 페이지 마크업

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Code12hour#5]
## 📄 설명
상품 리스트 페이지에서 상품 이미지를 눌렀을시 이동되는 상품 디테일 페이지 마크업

## 📋 TO-DO
- [ ] Product Detail 마크업
- [ ] Product Detail Navi 마크업
- [ ] Product Descrption 마크업
- [ ] Detail 마크업
