### ISSUE TITLE
헤더, 메인페이지 기능 구현 및 데이터 랜더링

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Code12hour#60]
## 📄 설명
1. 헤더, 메인페이지 기능 구현 완료 및 데이터 통신 완료하기
2. 빌드파일에서 구동시 상품 누르고 뒤로가기 누르면 최근 본 상품 업데이트가 되지 않는 버그 수정
3. 장바구니 아이템당 장바구니 위에 숫자로 뱃지 표시
4. 상품 눌렀을 때 해당 상품의 정보가 상세 페이지에 랜더링이 되도록 구현
5. 장바구니 페이지 진입 시 로컬 스토리지에 있는 데이터가 랜더링이 되도록 구현

## 📋 TO-DO

- [ ] 1. 헤더, 메인페이지 기능 구현 완료 및 데이터 통신 완료하기
- [x] 2. 빌드파일에서 구동시 상품 누르고 뒤로가기 누르면 최근 본 상품 업데이트가 되지 않는 버그 수정
- [x] 3. 장바구니 아이템당 장바구니 위에 숫자로 뱃지 표시
- [x] 4. 상품 눌렀을 때 해당 상품의 정보가 상세 페이지에 랜더링이 되도록 구현
- [ ] 5. 장바구니 페이지 진입 시 로컬 스토리지에 있는 데이터가 랜더링이 되도록 구현
- [x] 6. 장바구니를 성공적으로 담았다는 모달을 타이머 전에 닫아버리면 타이머가 지속 되는 현상 수정
- [x] 7. 상품 디테일 페이지에서 장바구니 담기 기능 구현
- [x] 8. 장바구니 아이템 로컬에 없을시 뱃지가 0으로 표현되는거 none처리
- [x] 9. 메인페이지 상품 카드에서 할인율이 없는 경우 기본 가격 하나만 표시되도록 처리

## 🔔 기타
기타 사항을 적어주세요.
