### ISSUE TITLE
장바구니 페이지 데이터 랜더링 및 마크업

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Code12hour#62]
## 📄 설명
장바구니 페이지 데이터 랜더링 및 마크업

## 📋 TO-DO

- [ ] 로컬스토리지에 저장 되어있는 product_id 값 가져와서 장바구니 페이지 냉동/냉장/상온 아코디언에 맞게 랜더링
- [ ] 아코디언 안에 상품들 마크업
- [ ] 총 장바구니 가격에 맞게 오른쪽 사이드바에 가격 표시
