### ISSUE TITLE
상품 디테일: 상품 후기, 문의 문서 수정 및 기타 버그 수정

### ISSUE THREAD

**Issue by soyeonpaark** [FRONTENDSCHOOL10/Code12hour#70]
## 📄 설명

상품 디테일: 상품 후기, 문의 문서 수정 및 기타 버그 수정

## 📋 TO-DO

- [x] 로그인 시 해당 사용자의 정보로 후기, 문의 등록 가능하게끔
- [x] 유저 이름 별표 (개인정보 마스킹 작업)
- [x] 비밀글 팝업창 안 뜨는 오류 수정
- [x] 로그인 알림창 (c-modal 사용)
- [x] 모달창 border: none; 디자인 수정
- [x] 모달창 해당 페이지 제품값 가져오기
- [x] 로그인 시 로그인 알림창과 후기 작성창 동시에 뜨는 버그
- [ ] 로그인 해도 입력창 이전에 로그인 알림창이 실행되는 버그
- [ ] 문의 비밀글 해당 작성자(=로그인)는 열람 가능

## 🔔 기타

기타 사항을 적어주세요.
