### ISSUE TITLE
최종 배포 전 각 페이지 수정

### ISSUE THREAD

**Issue by devHyeon99** [FRONTENDSCHOOL10/Code12hour#93]
## 📄 설명
최종 배포 전 각 페이지 수정

## 📋 TO-DO
- [x]  검색어 입력시 엔터도 가능하게 수정
- [x]  장바구니 담기 후 모달창 알림 뜰시 레이아웃 깨지는 현상 수정
- [ ]  장바구니 페이지 -> 상품 목록 X 아이콘 누를시 해당 제품 삭제 되도록 구현
- [x]  회원가입 기본 alert창 modal창으로 변경
- [x]  검색 필터 기준에 브랜드도 추가하기
- [ ]  주문하기 누르면 모달창에 주문한 목록들과 상품 모달창에 띄워주기?
- [x]  회원가입 페이지 header small타입 연결

## 🔔 기타

기타 사항을 적어주세요.
